ORM/orm_project/autenticacion/urls.py
# autenticacion/urls.py
from django.urls import path
from .views import CustomLoginView, SignUpView
from django.contrib.auth.views import LogoutView

app_name = 'autenticacion'

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='autenticacion:login'), name='logout'),
    path('signup/', SignUpView.as_view(), name='signup'),
]

ORM/orm_project/categoria/urls.py
from django.urls import path
from .views import CategoriaListView, CategoriaDetailView, categoria_crear, categoria_editar

app_name = 'categoria'

urlpatterns = [
    path('', CategoriaListView.as_view(), name='categoria_lista'),
    path('<int:pk>/', CategoriaDetailView.as_view(), name='categoria_detalle'),
    path('crear/', categoria_crear, name='categoria_crear'),
    path('editar/<int:pk>/', categoria_editar, name='categoria_editar'),
]

ORM/orm_project/etiqueta/urls.py
from django.urls import path
from .views import EtiquetaListView, EtiquetaDetailView, etiqueta_crear, etiqueta_editar

app_name = 'etiqueta'

urlpatterns = [
    path('', EtiquetaListView.as_view(), name='etiqueta_lista'),
    path('<int:pk>/', EtiquetaDetailView.as_view(), name='etiqueta_detalle'),
    path('crear/', etiqueta_crear, name='etiqueta_crear'),
    path('editar/<int:pk>/', etiqueta_editar, name='etiqueta_editar'),
]

ORM/orm_project/orm_project/urls.py
# orm_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView, TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('autenticacion/', include('autenticacion.urls')),
    path('categoria/', include('categoria.urls')),
    path('productos/', include('productos.urls')),
    path('etiqueta/', include('etiqueta.urls')),
    path('perfil/', include('perfil.urls')),
    path('home', TemplateView.as_view(template_name='home.html'), name='home'),  # URL para la página de inicio
    path('', RedirectView.as_view(url='autenticacion/login/', permanent=False)),  # Redirigir a la página de login en la raíz
]

ORM/orm_project/perfil/urls.py
# perfil/urls.py
from django.urls import path
from . import views
from .views import PerfilDetailView, PerfilUpdateView


app_name = 'perfil'

urlpatterns = [
    path('crear/', views.perfil_crear, name='perfil_crear'),
    path('detalle/', PerfilDetailView.as_view(), name='perfil_detalle'),
    path('editar/', PerfilUpdateView.as_view(), name='perfil_editar'),
]

ORM/orm_project/productos/urls.py
from django.urls import path
from .views import ProductoListView, ProductoDetailView, producto_crear, producto_editar

app_name = 'productos'

urlpatterns = [
    path('', ProductoListView.as_view(), name='producto_lista'),
    path('<int:pk>/', ProductoDetailView.as_view(), name='producto_detalle'),
    path('crear/', producto_crear, name='producto_crear'),
    path('editar/<int:pk>/', producto_editar, name='producto_editar'),
]

ORM/orm_project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Orm Proyecto</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <!-- Aquí agregaremos nuestros estilos personalizados -->
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <style>
    /* Body */
body {
    background: linear-gradient(to bottom, #704214, #c08d45); /* Degradado sepia */
    font-family: "Times New Roman", Times, serif; /* Cambia la fuente según tus preferencias */
    font-style: italic; /* Estilo cursivo para el texto del cuerpo */
    margin: 0; /* Elimina el margen por defecto */
    padding-bottom: 60px; /* Espacio para el footer */
    min-height: 100vh; /* Altura mínima de la ventana */
    display: flex;
    flex-direction: column;
}

/* Navbar */
#my_bar {
    background-color: #e8d5b7 !important; /* Fondo sepia claro */
    border: 1px solid #a17171; /* Borde sepia oscuro */
    font-family: "Times New Roman", Times, serif; /* Cambia la fuente según tus preferencias */
    font-style: italic; /* Estilo cursivo para el texto del cuerpo */
}

/* Main content */
main {
    flex: 1; /* Toma el espacio disponible en la página */
}

/* Footer */
.my_pie {
    text-align: center; /* Alineación del texto al centro */
    padding: 10px 0; /* Espaciado dentro del footer */
    width: 100%; /* Ancho completo */
    background-color: #e8d5b7; /* Fondo sepia claro */
    border-top: 1px solid #a17171; /* Borde superior sepia oscuro */
}

/* Efecto de zoom al pasar el mouse sobre el footer */
.my_pie:hover {
    transform: scale(1.1); /* Escala el footer al 110% al pasar el mouse sobre él */
    border-color: #704214; /* Borde sepia más oscuro */
    transition: transform 0.3s ease, border-color 0.3s ease; /* Animación suave */
}

  </style>
</head>
<body>
  <header>
      {% include "nav.html" %}
  </header>

  <main>
    {% block content %}
      <!-- Contenido específico de cada página -->
    {% endblock %}
  </main>

  <footer>
    {% include "footer.html" %}
  </footer>

  <!-- Agrega tus scripts JavaScript aquí -->
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
  <script src="{% static 'js/script.js' %}"></script> <!-- Aquí agregaremos nuestro script de JavaScript -->
</body>
</html>

ORM/orm_project/templates/footer.html
<!-- Contenido del pie de página -->
<footer id="my_pie" class="bg-light mt-5">
  <div class="container">
    <div class="card">
      <div class="card-header text-center">
        &copy;  Orm Projects
      </div>
      <div class="card-body">
        <blockquote class="blockquote mb-0 text-center">
          <p>Te ayudamos en la gestión de de productos relacionados</p>
          <footer class="blockquote-footer">Para facilitar tu trabajo <cite title="Source Title">De Logistica</cite></footer>
        </blockquote>
      </div>
    </div>
  </div>
</footer>

ORM/orm_project/templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header text-center">
                    <h2>Administración</h2>
                </div>
                <div class="card-body">
                    <div class="list-group">
                        <a href="{% url 'categoria:categoria_lista' %}" class="list-group-item list-group-item-action">
                            <h5 class="mb-1">Gestionar Categorías</h5>
                            <p class="mb-1">Administrar la lista de categorías, editar o añadir nuevas.</p>
                        </a>
                        <a href="{% url 'productos:producto_lista' %}" class="list-group-item list-group-item-action">
                            <h5 class="mb-1">Gestionar Productos</h5>
                            <p class="mb-1">Ver y editar la lista de productos disponibles.</p>
                        </a>
                        <a href="{% url 'etiqueta:etiqueta_lista' %}" class="list-group-item list-group-item-action">
                            <h5 class="mb-1">Gestionar Etiquetas</h5>
                            <p class="mb-1">Gestionar las etiquetas de los productos.</p>
                        </a>
                        <a href="{% url 'perfil:perfil_detalle' %}" class="list-group-item list-group-item-action">
                            <h5 class="mb-1">Perfil</h5>
                            <p class="mb-1">Editar la información del perfil del usuario.</p>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

ORM/orm_project/templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-transparent" id="my_bar">
    <a class="navbar-brand" href="{% url 'home' %}">
        <img src="{% static 'img/icono.png' %}" alt="Icono" width="30" height="30">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <ul class="navbar-nav">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link navbar-item btn" href="{% url 'categoria:categoria_lista' %}">Categorías</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link navbar-item btn" href="{% url 'productos:producto_lista' %}">Productos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link navbar-item btn" href="{% url 'etiqueta:etiqueta_lista' %}">Etiquetas</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link navbar-item btn" href="{% url 'perfil:perfil_detalle' %}">Perfil</a>
                </li>
                <li class="nav-item">
                    <form method="post" action="{% url 'autenticacion:logout' %}">
                        {% csrf_token %}
                        <button type="submit" class="nav-link navbar-item btn" style="border: none; padding: 0; background: none; cursor: pointer;">Logout</button>
                    </form>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link navbar-item btn" href="{% url 'autenticacion:signup' %}">Registrarse</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link navbar-item btn" href="{% url 'autenticacion:login' %}">Iniciar Sesión</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>